public enum AcornScripting: String {
    case application = "application"
    case attachment = "attachment"
    case attributeRun = "attribute run"
    case bitmapLayer = "bitmap layer"
    case box = "box"
    case character = "character"
    case circle = "circle"
    case document = "document"
    case graphic = "graphic"
    case groupLayer = "group layer"
    case image = "image"
    case layer = "layer"
    case paragraph = "paragraph"
    case path = "path"
    case richText = "rich text"
    case shapeLayer = "shape layer"
    case textArea = "text area"
    case window = "window"
    case word = "word"
}
