public enum AcornScriptingClass: String {
    case Application = "application"
    case Window = "window"
    case RichText = "rich text"
    case Character = "character"
    case Paragraph = "paragraph"
    case Word = "word"
    case AttributeRun = "attribute run"
    case Attachment = "attachment"
    case Document = "document"
    case Graphic = "graphic"
    case Box = "box"
    case Circle = "circle"
    case Image = "image"
    case Line = "line"
    case TextArea = "text area"
    case Layer = "layer"
    case BitmapLayer = "bitmap layer"
    case GroupLayer = "group layer"
    case ShapeLayer = "shape layer"
}
