public enum PagesScripting: String {
    case template = "template"
    case section = "section"
    case page = "page"
    case richText = "rich text"
    case character = "character"
    case paragraph = "paragraph"
    case word = "word"
    case placeholderText = "placeholder text"
    case iworkContainer = "iWork container"
    case iworkItem = "iWork item"
    case audioClip = "audio clip"
    case shape = "shape"
    case chart = "chart"
    case image = "image"
    case group = "group"
    case line = "line"
    case movie = "movie"
    case table = "table"
    case textItem = "text item"
    case range = "range"
    case cell = "cell"
    case row = "row"
    case column = "column"
}
