public enum ImageEventsScripting: String {
    case classicDomainObject = "Classic domain object"
    case alias = "alias"
    case application = "application"
    case diskItem = "disk item"
    case disk = "disk"
    case display = "display"
    case domain = "domain"
    case filePackage = "file package"
    case file = "file"
    case folder = "folder"
    case image = "image"
    case localDomainObject = "local domain object"
    case metadataTag = "metadata tag"
    case networkDomainObject = "network domain object"
    case profile = "profile"
    case systemDomainObject = "system domain object"
    case userDomainObject = "user domain object"
}
